package com.dfdyz.ecos_j;

public class Stats {
    public double pcost;
    public double dcost;
    public double pres;
    public double dres;
    public double pinf;
    public double dinf;
    public double pinfres;
    public double dinfres;
    public double gap;
    public double relgap;
    public double sigma;
    public double mu;
    public double step;
    public double step_aff;
    public double kapovert;
    public int iter;
    public int nitref1;
    public int nitref2;
    public int nitref3;
    public double tsetup;
    public double tsolve;
    public double tfactor;
    public double tkktsolve;
    public double torder;
    public double tkktcreate;
    public double ttranspose;
    public double tperm;
    public double tfactor_t1;
    public double tfactor_t2;
    public int pob;
    public int cb;
    public int cob;
    public int pb;
    public int db;
    public int affBack;
    public int cmbBack;
    public double centrality;
}
